room/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('roomate_app.urls'))
]

roomate_app/urls.py
from django.urls import path, re_path
from django.conf.urls import url, include


from . import views

app_name = 'roomate_app'
urlpatterns = [ 
    # Home page
    path('', views.index, name='index'),
    url(r'^delete/(?P<chore_id>[0-9]+)/$', views.delete_chore, name='delete_a_chore'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('newapt/', views.new_apt, name='newApartment'),
    path('joinapt/', views.assign_apt, name='joinApartment'),
    path('profile/', views.profile, name='profile'),
    path('newchore/', views.new_chore, name='newChore'),
    path('leaveapt/', views.leave_apt, name='leaveApt'),
    url(r'^complete/(?P<chore_id>[0-9]+)/$', views.complete_chore, name='completeChore'),
]

templates/partials/_footer.html
<footer id="main-footer" class="py-3 bg-info text-blue text-center fixed-bottom">
  <span class="text-white"></span> Send us money, Venmo: @fourbears
</footer>

templates/partials/_navbar.html
{% if request.user.is_authenticated %}
  <nav id="navbar" class="navbar navbar-expand-lg navbar-dark bg-transparent">
    <a class="navbar-brand font-weight-bold" href="{% url 'roomate_app:index' %}"><h3>RoomPals</h3></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'roomate_app:profile' %}"><i class="fas fa-user trash"></i>Profile</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link text-white" href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt trash"></i>Logout</a>
        </li>
      </ul>
    </div>
  </nav>
 
{% else %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
    <a class="navbar-brand font-weight-bold" href="{% url 'roomate_app:index' %}"><h3>RoomPals</h3></a>
  </nav>
{% endif %}