room/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('roomate_app.urls'))
]

roomate_app/urls.py
from django.urls import path, re_path
from django.conf.urls import url, include


from . import views

app_name = 'roomate_app'
urlpatterns = [ 
    # Home page
    path('', views.index, name='index'),
    url(r'^delete/(?P<chore_id>[0-9]+)/$', views.delete_chore, name='delete_a_chore'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('newapt/', views.new_apt, name='newApartment'),
    path('joinapt/', views.assign_apt, name='joinApartment'),
    path('profile/', views.profile, name='profile'),
    path('newchore/', views.new_chore, name='newChore'),
    path('leaveapt/', views.leave_apt, name='leaveApt'),
    url(r'^complete/(?P<chore_id>[0-9]+)/$', views.complete_chore, name='completeChore'),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as views_builtin
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from . import forms
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', CreateView.as_view(template_name='registration/register.html',
        form_class=forms.RegisterUserForm, 
        success_url=reverse_lazy('roomate_app:dashboard')), name='register'),
    path("change_password/", views.change_password, name='change_password')
    

]

roomate_app/models.py
from django.db import models
from django.contrib.auth.models import User
import json
import secrets
from django.db.models.signals import post_save
from django.dispatch import receiver
from hashlib import sha1
from django.utils.crypto import get_random_string
# Create your models here.


class Apartment(models.Model):
    apt_id = models.AutoField(primary_key=True)
    date_added = models.DateTimeField(auto_now_add=True)
    token = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "apartments"

    def __str__(self):
        return "Apartment " + str(self.apt_id)


class MyUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    myApt = models.ForeignKey(Apartment, null=True, on_delete=models.SET_NULL)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "myusers"

@receiver(post_save, sender=User)
def create_user_myuser(sender, instance, created, **kwargs):
    if created:
        MyUser.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_myuser(sender, instance, **kwargs):
    instance.myuser.save()


class Chore(models.Model):
    apt_id = models.ForeignKey(Apartment, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    creator = models.ForeignKey(User, null=False, on_delete=models.CASCADE, related_name='creator_user')
    assignees = models.ManyToManyField(User, blank=True)
    description = models.CharField(max_length=500, default="Description of Chore")
    complete = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def set_assignees(self, nameList):
        self.assignees = json.dumps(nameList)

    def get_assignees(self):
        return json.loads(self.assignees)

    class Meta:
        verbose_name_plural = "chores"

    def __str__(self):
        return self.name

roomate_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import MyUser, Apartment, Chore

class JoinApartmentForm(forms.Form):
    apt_token = forms.CharField()

class CreateChoreForm(forms.ModelForm):
    class Meta:
        model = Chore
        fields = ['name', 'description', 'assignees']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(CreateChoreForm, self).__init__(*args, **kwargs)

        my_user = self.user.myuser
        myusers = MyUser.objects.filter(myApt=my_user.myApt)
        self.fields['assignees'].queryset = User.objects.filter(myuser__in=myusers)
        #users = []
        #myUsers = MyUser.objects.filter(myApt=self.user.myuser.myApt)
        #for myUser in myUsers:
        #    if self.user.username != myUser.user.username:
        #        users.append((self.user, myUser.user))

roomate_app/views.py
from django.shortcuts import render, redirect
from .models import Apartment, MyUser, Chore
from django.contrib.auth.models import User
from .forms import JoinApartmentForm, CreateChoreForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from hashlib import sha1
import secrets

# Create your views here.
def index(request):
    if request.user.is_authenticated:  
        return redirect('roomate_app:dashboard')
    return render(request, 'roomate_app/index.html')

@login_required
def dashboard(request):
    #check if the user has an apartment or not
    chores = Chore.objects.filter(apt_id=request.user.myuser.myApt)
    return render(request, 'roomate_app/dashboard.html', {'chores': chores})

#Create a new apartment.
@login_required
def new_apt(request):
    if request.method != 'POST':
        #need to raise a flash here
        messages.warning(request, 'Failed To Create An Apartment. Please try again.')
        return redirect('roomate_app:dashboard')
    
    current_user = request.user
    my_apartment = Apartment.objects.create()
    my_apartment.token = sha1((secrets.token_hex() + str(my_apartment.pk)).encode('utf-8')).hexdigest()
    current_user.myuser.myApt = my_apartment
    my_apartment.save()
    current_user.save()
    return redirect('roomate_app:dashboard')

#Get an existing apartment.
@login_required
def assign_apt(request):
    current_user = request.user
    if request.method == 'POST':
        form = JoinApartmentForm(request.POST)
        if form.is_valid():
            input_token = form.cleaned_data['apt_token']
            apt_list = Apartment.objects.filter(token=input_token)
            if apt_list.count() > 0:
                apt = Apartment.objects.get(token=input_token)
                current_user.myuser.myApt = apt
                current_user.save()
                return redirect('roomate_app:dashboard')
            else:
                #need to raise a flash here
                messages.warning(request, 'Failed To Join An Apartment. Please Verify Your Token.')
                form = JoinApartmentForm()
    else:
        #need to raise a flash here
        form = JoinApartmentForm()

    context = {'form': form}
    return render(request, 'roomate_app/joinApartment.html', context)

#Create a new chore
@login_required
def new_chore(request):
    current_user = request.user
    apt_id = current_user.myuser.myApt
    if request.method == 'POST':
        form = CreateChoreForm(request.POST, user=current_user)
        if form.is_valid():
            input_name = form.cleaned_data['name']
            input_desc = form.cleaned_data['description']
            input_assignees = form.cleaned_data['assignees']
            new_chore_obj = Chore(apt_id=apt_id, name=input_name, creator=current_user, description=input_desc)
            new_chore_obj.save()
            for assignee in input_assignees:
                new_chore_obj.assignees.add(User.objects.get(username=assignee))
            #messages.success(request, 'You have successfully created a Chore!')
            return redirect('roomate_app:dashboard')
    
    else:
        form = CreateChoreForm(user=current_user)
        
    numUsers = MyUser.objects.filter(myApt=apt_id).count()
    context = {'form': form, 'numUsers': numUsers }
    return render(request, 'roomate_app/newChore.html', context)

@login_required
def delete_chore(request, chore_id =None):
    chore_object = Chore.objects.get(id=chore_id)
    chore_object.delete()
    messages.warning(request, 'Successfully delete.')
    return redirect('roomate_app:dashboard')

@login_required
def profile(request): 
    username = request.user.username
    email = request.user.email
    my_user = request.user.myuser
    apt = my_user.myApt
    apt_token = ""
    if apt == None:
        apt_token = "You are not in an Apartment"
    else:
        apt_token = apt.token
    context = {'username': username, 'email': email, 'apt_token': apt_token}
    return render(request, 'roomate_app/profile.html', context)

@login_required
def leave_apt(request):
    if request.method != 'POST':
        #need to raise a flash here
        messages.warning(request, 'Failed to leave the Apartment. Please try again.')
        return redirect('roomate_app:dashboard')

    current_user = request.user
    apt_id = current_user.myuser.myApt

    my_user = current_user.myuser
    roommates = MyUser.objects.filter(myApt=apt_id)
    if roommates.count() == 1:
        my_user.myApt.delete()

    my_user.myApt = None
    my_user.save()
    return render(request, 'roomate_app/dashboard.html')

@login_required
def complete_chore(request, chore_id=None):
    chore_obj = Chore.objects.get(id=chore_id)
    chore_obj.delete()
    return redirect('roomate_app:dashboard')

templates/roomate_app/dashboard.html
{% extends "base.html" %} 
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-primary" role="alert">
        {{ message }}
    </div>
    {% endfor %}
</ul>
{% endif %}
{% if user.myuser.myApt %}
    {% if chores %}
        <ul class="ul-padding">
        {% for c in chores %}
            <div class="container w-100 h-75 chores-size">
                <div class="row h-100 justify-content-center align-items-center">
                    <div id="card" class="card mb-3 w-100">
                        <div class="card-header">
                            {{ c.name }}
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-9 pull-md-3 mb-2">
                                    <p> Description: {{ c.description }} </p>
                                    <p> Creator: {{ c.creator.username }} </p>
                                    <div>
                                        Assignees:
                                        {% for a in c.assignees.all %}
                                            {{ a }}
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="col-md-3 push-md-9 text-right">
                                    <div class="d-flex flex-column">
                                        <a class="btn btn-info chores-btn-size" href="{% url 'roomate_app:completeChore' c.id%}"><i class="fa fa-check trash"></i> Complete</a>
                                        <a class="btn btn-danger chores-btn-size" href="{% url 'roomate_app:delete_a_chore' c.id%}"><i class="fa fa-trash trash"></i>Delete</a>
                                    </div>
                                </div>
                            </div>    
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="container w-100 h-100 chores-size">
            <div class="row h-100 justify-content-center align-items-center">
                <a class="btn btn-outline-light font-weight-bold btn-lg btn-block chore-btn-size" href="{% url 'roomate_app:newChore' %}" role="button" name="createchore">
                    <div class="vertical">Create a new Chore</div>
                </a>
            </div>
        </div>
        </ul>
    {% else %}
    <div class="container-fluid w-100 h-75 chores-size">
        <div class="row h-100 justify-content-center align-items-center">
            <a class="btn btn-outline-light btn-xl" href="{% url 'roomate_app:newChore' %}" role="button" name="createchore">
                <div class="vertical">Create a new Chore</div>
            </a>
        </div>
    </div>
    {% endif %}
{% else %}
<div class="container-fluid h-75">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="card profile-card ml-3 mr-3 bg-card">
            <div class="card-body text-white d-flex flex-column justify-content-center align-items-center">
                <div>
                    <form method="post" action="{% url 'roomate_app:newApartment' %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-light btn-lg apt-btn-space" name="submit" id="create-apt">Create a new Apartment</button>
                        <input type="hidden" name="next" value="{% url 'roomate_app:dashboard' %}"/>
                    </form>
                </div>
                <div>
                    <a class="btn btn-outline-light btn-lg apt-btn-space" href="{% url 'roomate_app:joinApartment' %}" role="button" id="join-apt">Join an existing Apartment</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

templates/roomate_app/index.html
{% extends "base.html" %}
{% block content %}

<div class="container h-75">
  <div class="row h-100 justify-content-center align-items-center">
    <div id="card" class="card text-center mb-3 card-size-home bg-card">
      <div class="card-body align-items-center">
        <h5 class="text-white card-title">Welcome to RoomPals!</h5>
        <div>
          <a class="btn btn-outline-light btn-space" href="{% url 'users:login' %}" role="button">Login</a>
        </div>
        <div>
          <a class="btn btn-outline-light btn-space" href="{% url 'users:register' %}" role="button">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/roomate_app/joinApartment.html
{% extends "base.html" %} 
{% block content %}
<div class="container h-75">
    <div class="row h-100 justify-content-center align-items-center">
        <div id="card" class="card mb-3 bg-card card-size-apt bg-custom-1">
            <div class="card-header text-white font-weight-bold text-center">
                <h4>Enter the Apartment token</h4>
              </div>
            <div class="card-body">
                <form method="post" action="{% url 'roomate_app:joinApartment' %}">
                    {% csrf_token %}
                    <label for="{{ form.apt_token.id_for_label }}" class="sr-only">Apartment Token</label>
                    <input type="apt_token text-white" id="{{ form.apt_token.id_for_label }}" name="{{ form.apt_token.html_name }}" class="form-control bg-form-bar" placeholder="Apartment Token" required>
                    {% if messages %}
                        {% for message in messages %}
                            <p class="error-font">{{ message }}</p>
                        {% endfor %}
                    {% endif %}
                    <button class="btn btn-outline-light btn-block form-space" name="submit">Enter</button>
                    <input type="hidden" name="next" value="{% url 'roomate_app:dashboard' %}"/>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/roomate_app/newChore.html
{% extends "base.html" %} 
{% block content %}
{% load widget_tweaks %}
<div class="container h-75">
    <div class="row h-100 justify-content-center align-items-center">
        <div id="card" class="card mb-3 chore-card-size">
            <div class="card-header">
                Create a new Chore
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'roomate_app:newChore' %}">
                    {% csrf_token %}
                    <input type="hidden" id="num-users" name="num-users" value="{{ numUsers }}">
                    <label for="{{ form.name.id_for_label }}" class="sr-only">Name</label>
                    <input type="name" id="{{ form.name.id_for_label }}" name="{{ form.name.html_name }}" class="form-control chore-form-space" placeholder="Name" required>
                    <label for="{{ form.description.id_for_label }}" class="sr-only">Description</label>
                    <textarea id="{{ form.description.id_for_label }}" name="{{ form.description.html_name }}" class="form-control chore-form-space" placeholder="Description" required></textarea>
                    {% render_field form.assignees id="assignees" class="selectpicker chore-form-space" name="assignees" data-live-search="true" title="Pick an Assignee" %}<br>

                    {% if messages %}
                        {% for message in messages %}
                            <p class="error-font">{{ message }}</p>
                        {% endfor %}
                    {% endif %}
                    <button class="btn btn-info form-space" name="submit">Enter</button>
                    <input type="hidden" name="next" value="{% url 'roomate_app:dashboard' %}"/>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/roomate_app/profile.html
{% extends "base.html" %} 
{% block content %}

<div class="container h-75">
  <div class="row h-100 justify-content-center align-items-center">
    <div class="card profile-card ml-3 mr-3 bg-card">
        <div class="card-body text-white d-flex flex-column">
          <div class="row">
            <div class="col-md-4 pull-md-8 text-left">
              <p>Username: </p>
            </div>
            <div class="col-md-8 push-md-4 text-left">
              <p>{{ username }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 pull-md-8 text-left">
              <p>Email: </p>
            </div>
            <div class="col-md-8 push-md-4 text-left">
              <p>{{ email }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 pull-md-8 text-left">
              <p>Join Apartment Token: </p>
            </div>
            <div class="col-md-8 push-md-4 text-left">
              <p>{{ apt_token }}</p>
            </div>
          </div>
          <div class="mt-auto">
            <form method="post" action="{% url 'users:change_password' %}">
              {% csrf_token %}
              <button class="btn btn-outline-light font-weight-bold btn-block" name="submit">Change Password</button>
              <input type="hidden" name="next" value="{% url 'roomate_app:dashboard' %}"/>
            </form>
            <form method="post" action="{% url 'roomate_app:leaveApt' %}" class="margin">
              {% csrf_token %}
              <button class="btn btn-danger font-weight-bold btn-block leave-color" name="submit-leave">Leave the current Apartment</button>
              <input type="hidden" name="next" value="{% url 'roomate_app:dashboard' %}"/>
            </form>
          </div>
        </div>
    </div>
  </div>
</div>
{% endblock content %}